### PR TITLE
BREAKING CHANGE: Validate against non-string types, remove optional field logic from all validators

### PR DESCRIPTION
**Pull request by ArrayKnight**
`undefined`, `null`, and empty strings all fail.

strings are trimmed first, so `' '` becomes `''` which fails.

### CODE REVIEW

**Comment by selbekk** [comment]
I disagree with the removal of "the empty string bypass". 

The reason all empty strings are valid, is so you can validate fields that are not required. So an optional email address can be required to be a valid email address, if you pass it anything at all. 

I understand `calidators` now can solve this via other means, but I don't see the upside of doing it this way. Care to elaborate your thoughts?

**Comment by ArrayKnight** [comment]
Yea, my bad.

My expectations are that validators do exactly what they say they are. I would think they have a single responsibility of determining whether the value matches the criteria of the test, not whether it's optional.

I would put the logic for determining if a field is optional within Calidation's `Form.validateField` method.

Something like:
```
// if field is optional and the value doesn't pass the isRequired validator, skip all validators
if (!fieldValidators.isRequired && this.props.validators.isRequired({...}, {...})(allFields[fieldName]) !== null) {
    return null
} else {
   return Object.entries(fieldValidators).reduce(...)
}
```

**Comment by selbekk** [comment]
Although I appreciate your points, and understand where you're coming from - I'm still not a fan of introducing this change. There are a couple of reasons.

First, this breaks with the initial design, which in turn will lead to this being a pretty breaking change for a lot of people. People will have to add a lot of `validateIf` logic to their remaining validators, and it'll be harder to write validators for optional fields (imo).

Second, by having a separate validator for required fields, you get to compose together functionality in a way. That's why I feel like the `isEmail` validator does what it says on the tin, given that its supposed to be composed together with the `isRequired` validator if you want it to be required. This works the same way as the `input` attributes `type="email"` and `required` ([CodeSandbox example](https://codesandbox.io/s/xlvzy2xvmw)). 

There are other ways around the issue with transforming values

**Comment by ArrayKnight** [comment]
If we make the above change to `Form.validateField` there will be no change in how validators are implemented. You wouldn't need a `validateIf` and you would still be able to have optional or required fields.

The functionality would be identical to today and to the native HTML example you provided.

**Comment by ArrayKnight** [comment]
@selbekk I'd really appreciate it if you would reconsider this. I honestly think this is the best route. I've also talked it through with a couple of my coworkers who also expressed a similar opinion.

**Comment by selbekk** [comment]
Hm, well fair enough. Should we write some kind of migration guide for people already using this?

**Comment by ArrayKnight** [comment]
I'm about to push up some changes that are still a work in progress, so don't mind the PR any attention. I'll remove the WIP from the title and ping you when I've got things tidied up.

Sorry for the long delay btw, I've been quite busy. But I'm hoping to get some more time in this week and next. I hope things are going well on your end. I have been reading your articles about creating a validation library from scratch using React hooks. Some pretty interesting stuff happening there!

**Comment by ArrayKnight** [comment]
Here's the pending PR on the Calidation side: https://github.com/selbekk/calidation/pull/53

**Comment by selbekk** [comment]
That's a wowser of a pull request. Scanned through it - looks fine by me. 

Except for the required-piece - will the validators work like they do today, or is there a change in how their default behavior will be? If it's the latter, we need to list this in the breaking changes

**Pull request merged**
