### PR TITLE
Improve isEmail validation

### PR DESCRIPTION
**Pull request by davidbucka**
fixes validating values without e.g. `.com`

### CODE REVIEW

**Comment by selbekk** [comment]
Hi @davidbucka - thanks for the pull request!

I'm not a great Regex-er, so could you please try to explain what this regex allows and doesn't?

Also, in order to add this, I need to cut a breaking change release (new major). Isn't the soft validation that's in place now good enough to provide a front-end hint to the user that they might have done a mistake?

Finally, I'd love to see some tests as well :)

**Comment by epitaphmike** [comment]
You could always use the [email regex](https://github.com/jquense/yup/blob/00ad803c79e12dfa4b1d485dcd5aac9783dcf027/src/string.js#L7) in the [yup](https://github.com/jquense/yup) library as well. It is thoroughly tested.

```
// eslint-disable-next-line
let rEmail = /^((([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*)|((\x22)((((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(([\x01-\x08\x0b\x0c\x0e-\x1f\x7f]|\x21|[\x23-\x5b]|[\x5d-\x7e]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(\\([\x01-\x09\x0b\x0c\x0d-\x7f]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))))*(((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(\x22)))@((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))$/i;
```

**Comment by selbekk** [comment]
> You could always use the [email regex](https://github.com/jquense/yup/blob/00ad803c79e12dfa4b1d485dcd5aac9783dcf027/src/string.js#L7) from the [yup](https://github.com/jquense/yup) library as well. It is thoroughly tested.
> 
> ```
> // eslint-disable-next-line
> let rEmail = /^((([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*)|((\x22)((((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(([\x01-\x08\x0b\x0c\x0e-\x1f\x7f]|\x21|[\x23-\x5b]|[\x5d-\x7e]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(\\([\x01-\x09\x0b\x0c\x0d-\x7f]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))))*(((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(\x22)))@((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))$/i;
> ```

There's tons of email validation regexes out there. I'm sure this is a great one, but I think my points from above still stands. A "soft" validation makes sure we catch most spelling errors and typos, while the backend validation framework could do a stricter validation.

I could add an option to the validator indicating the strictness, perhaps? That wouldn't be a breaking change.

**Comment by epitaphmike** [comment]
> A "soft" validation makes sure we catch most spelling errors and typos

I don't know. Personally I'd prefer the client to catch a little more. In the current test an email address like `R@D` is considered valid. 

It may rad, but it's not valid 😆

**Comment by selbekk** [comment]
Yeah I understand your point of view. :) r@localhost is a valid email though!

**Comment by selbekk** [comment]
What about `whatever@whatever.whatever`?

**Comment by selbekk** [comment]
Hi there! I merged in #7, that supercedes this PR. Thanks for the inspiration and great discussion!

**Pull request closed without merging**
