### PR TITLE
feat: added validator hasLowercase

### PR DESCRIPTION
**Pull request by iamwtk**

### CODE REVIEW

**Comment by selbekk** [comment]
Hi! Thanks for this pull request. What's your usecase for having such a validator?

**Comment by iamwtk** [comment]
I have on back-end password validation for lowercase, uppercase and digit in there, and want the same in front-end using your calidation component. First I made it via matchRegex but I wanted to have different error message for each rule, thus I added these validators and if you merge them I will add them to calidation too.

**Comment by selbekk** [comment]
Makes sense. Sure!

**Pull request merged**
